#
# Pull Request tasks
#

task:
  only_if: $CIRRUS_PR != ''

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3

  name: "PR: arm64-apple-darwin"

  install_script:
    - bash .ci-scripts/MacOS-arm64-install-pony-tools.bash release

  test_script:
    - export PATH="/tmp/ponyc/bin/:$PATH"
    - make test

#
# Nightly build tasks
#

task:
  only_if: $CIRRUS_CRON == "nightly"

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3

  name: "nightly: arm64-apple-darwin"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[fd6a633b6b830c0558d7553d2b1e899b48a47f82037c764ac15febb69a49a53e7415573562f89675ecca9d4e8d6c4969]
    GITHUB_REPOSITORY: ponylang/corral

  install_script:
    - brew install coreutils
    - brew install python
    - pip3 install --upgrade cloudsmith-cli
    - bash .ci-scripts/MacOS-arm64-install-pony-tools.bash release

  nightly_script:
    - export PATH="/tmp/ponyc/bin/:/Users/admin/Library/Python/3.8/bin:$PATH"
    - bash .ci-scripts/release/arm64-apple-darwin-nightly.bash

#
# Release build tasks
#

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3

  name: "release: arm64-apple-darwin"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[fd6a633b6b830c0558d7553d2b1e899b48a47f82037c764ac15febb69a49a53e7415573562f89675ecca9d4e8d6c4969]
    GITHUB_REPOSITORY: ponylang/corral

  install_script:
    - brew install coreutils
    - brew install python
    - pip3 install --upgrade cloudsmith-cli
    - bash .ci-scripts/MacOS-arm64-install-pony-tools.bash release

  release_script:
    - export PATH="/tmp/ponyc/bin/:/Users/admin/Library/Python/3.8/bin:$PATH"
    - bash .ci-scripts/release/arm64-apple-darwin-release.bash
