#
# Pull Request tasks
#

task:
  only_if: $CIRRUS_PR != ''

  freebsd_instance:
    image: freebsd-13-0-release-amd64

  name: "PR: x86-64-unknown-freebsd-13.0"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash git gmake
    - bash .ci-scripts/freebsd-13.0-install-pony-tools.bash release

  test_script:
    - export PATH="$HOME/.local/share/ponyup/bin/:$PATH"
    - gmake test

#
# Nightly build tasks
#

task:
  only_if: $CIRRUS_CRON == "nightly"

  freebsd_instance:
    image: freebsd-13-0-release-amd64

  name: "nightly: x86-64-unknown-freebsd-13.0"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[fd6a633b6b830c0558d7553d2b1e899b48a47f82037c764ac15febb69a49a53e7415573562f89675ecca9d4e8d6c4969]
    GITHUB_REPOSITORY: ponylang/corral

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash gmake git py38-pip
    - pip install --upgrade cloudsmith-cli
    - bash .ci-scripts/freebsd-13.0-install-pony-tools.bash

  nightly_script:
    - export PATH="$HOME/.local/share/ponyup/bin/:$PATH"
    - bash .ci-scripts/release/x86-64-unknown-freebsd-13.0-nightly.bash release

#
# Release build tasks
#

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  freebsd_instance:
    image: freebsd-13-0-release-amd64

  name: "release: x86-64-unknown-freebsd-13.0"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[fd6a633b6b830c0558d7553d2b1e899b48a47f82037c764ac15febb69a49a53e7415573562f89675ecca9d4e8d6c4969]
    GITHUB_REPOSITORY: ponylang/corral

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash gmake git py38-pip
    - pip install --upgrade cloudsmith-cli
    - bash .ci-scripts/freebsd-13.0-install-pony-tools.bash release

  release_script:
    - export PATH="$HOME/.local/share/ponyup/bin/:$PATH"
    - bash .ci-scripts/release/x86-64-unknown-freebsd-13.0-release.bash
