name: Windows ponyc update breakage test

on:
  repository_dispatch:
    types: [ponyc-windows-nightly-released]

jobs:
  windows:
    name: Verify main against the latest ponyc on Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Test with most recent ponyc nightly
        run: |
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/nightlies/raw/versions/latest/ponyc-x86-64-pc-windows-msvc.zip -OutFile C:\ponyc.zip;
          Expand-Archive -Path C:\ponyc.zip -DestinationPath C:\ponyc;
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
          .\make.ps1 -Command unit-tests 2>&1
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
