name: macOS ponyc update breakage test

on:
  repository_dispatch:
    types: [ponyc-macos-nightly-released]

jobs:
  macos:
    name: Verify main against the latest ponyc on macOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: install ponyc
        run: bash .ci-scripts/macOS-x86-install-pony-tools.bash nightly
      - name: brew install dependencies
        run: brew install coreutils
      - name: Test with most recent ponyc release
        run: |
          export PATH="/tmp/ponyc/bin/:$PATH"
          make unit-tests config=debug
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
