name: macOS ponyc update breakage test

on:
  repository_dispatch:
    types: [ponyc-macos-nightly-released]

jobs:
  macos:
    name: Verify main against the latest ponyc on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ponyc
        run: bash .ci-scripts/macOS-install-pony-tools.bash nightly
      - name: brew install dependencies
        run: brew install coreutils
      - name: Test with most recent ponyc release
        run: |
          export PATH="$HOME/.local/share/ponyup/bin/:$PATH"
          make test
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip@35d7ad8e98444f894dcfe1d4e17332581d28ebeb
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
