name: Changelog Bot

on:
  push:
    branches:
      - master
    paths-ignore:
      - CHANGELOG.md

jobs:
  changelog-bot:
    runs-on: ubuntu-latest
    name: Update CHANGELOG.md
    steps:
      - name: Update Changelog
        uses: ponylang/changelog-bot-action@0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
